### ISSUE TITLE
Bug: merging assertion failed

### ISSUE THREAD

**Issue by voltrevo** [voltrevo/CircuitScript#5]
input

```ts
export default function main(b0: number, b1: number, b2: number, x: number, y: number) {
  let b10 = (b0 & b1 & b2) & 1;

  if (b10 === 1) {
    return x + y;
  }

  return b10 + x < y;
}
```

output

```
thread 'main' panicked at compiler/src/arithmetic_merge.rs:159:5:
assertion failed: right.typeof_() == type_
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by voltrevo** [comment]
This is more of a bad error message than a bug. [I have improved this](https://github.com/voltrevo/summon/commit/fd3736caff4dd822da2d3110e70bc1f85dc1578d), now the output is:

```
thread 'main' panicked at compiler/src/arithmetic_merge.rs:160:5:
Cannot merge bool with number
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The issue is indeed that we can't merge a bool with a number. This merge occurs in the program above because the first return statement:

```ts
return x + y;
```

tries to return a number, while the other return statement:

```ts
return b10 + x < y;
```

tries to return a bool.

If false should mean 0 and true should mean 1, this can be achieved like this:

```ts
export default function main(b0: number, b1: number, b2: number, x: number, y: number) {
  let b10 = (b0 & b1 & b2) & 1;

  if (b10 === 1) {
    return x + y;
  }

  return toNumber(b10 + x < y);
}

function toNumber(b: boolean) {
  return b ? 1 : 0;
}
```
